# Generated by Django 4.2.1 on 2023-09-10 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0005_rename_author_author_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="subscribers",
            field=models.ManyToManyField(
                related_name="categories", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
